package statusline

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/eljaska/claustomize/internal/block"
)

const (
	separator    = " | "
	scriptHeader = `#!/bin/bash
# Generated by claustomize. Edits will be overwritten.
set -e
input=$(cat)
parts=()
`
)

// Generate returns the shell script content that renders the statusline.
func Generate(blocks []block.Block) string {
	var b strings.Builder
	b.WriteString(scriptHeader)
	for _, blk := range blocks {
		fmt.Fprintf(&b, "\nsegment=$(%s)\n[ -n \"$segment\" ] && parts+=(\"$segment\")\n", blk.Snippet)
	}
	fmt.Fprintf(&b, "\nresult=\"\"\nfor p in \"${parts[@]}\"; do\n  if [ -n \"$result\" ]; then result=\"$result%s$p\"; else result=\"$p\"; fi\ndone\necho \"$result\"\n", separator)
	return b.String()
}

// Preview runs the generated script against a sample stdin payload and
// returns the resulting line (or an error message suitable for display).
func Preview(blocks []block.Block) string {
	if len(blocks) == 0 {
		return "(no blocks selected)"
	}
	script := Generate(blocks)
	sample := `{"model":{"display_name":"Opus 4.7"},"workspace":{"current_dir":"` + sampleCwd() + `"}}`

	cmd := exec.Command("bash", "-c", script)
	cmd.Stdin = strings.NewReader(sample)
	var out, errBuf bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		return fmt.Sprintf("(preview error: %s)", strings.TrimSpace(errBuf.String()))
	}
	return strings.TrimRight(out.String(), "\n")
}

func sampleCwd() string {
	if cwd, err := os.Getwd(); err == nil {
		return cwd
	}
	return "/tmp"
}

// ScriptPath returns the absolute path where the generated script is stored.
func ScriptPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "claustomize", "statusline.sh"), nil
}

// SettingsPath returns the path to Claude Code's user settings.json.
func SettingsPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "settings.json"), nil
}

// Install writes the generated script to disk and updates settings.json to
// reference it. Existing settings.json fields are preserved.
func Install(blocks []block.Block) error {
	scriptPath, err := ScriptPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0o755); err != nil {
		return fmt.Errorf("create script dir: %w", err)
	}
	if err := os.WriteFile(scriptPath, []byte(Generate(blocks)), 0o755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}

	settingsPath, err := SettingsPath()
	if err != nil {
		return err
	}
	if err := updateSettings(settingsPath, scriptPath); err != nil {
		return fmt.Errorf("update settings: %w", err)
	}
	return nil
}

func updateSettings(settingsPath, scriptPath string) error {
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return err
	}

	settings := map[string]any{}
	if data, err := os.ReadFile(settingsPath); err == nil && len(data) > 0 {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parse existing settings: %w", err)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}

	settings["statusLine"] = map[string]any{
		"type":    "command",
		"command": scriptPath,
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(settingsPath, append(out, '\n'), 0o644)
}
