package statusline

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/eljaska/claustomize/internal/slot"
)

const scriptHeader = `#!/bin/bash
# Generated by claustomize. Edits will be overwritten.
set -e
input=$(cat)
out=""
`

// Generate returns the shell script that renders the statusline composed
// from the filled slots in the given list. Empty slots emit nothing;
// separator visuals come from explicit separator blocks the user places.
func Generate(slots slot.List) string {
	var b strings.Builder
	b.WriteString(scriptHeader)
	for _, s := range slots {
		if s.IsEmpty() {
			continue
		}
		snippet := s.Block.Styles[s.StyleIdx].Snippet
		fmt.Fprintf(&b, "\nout=\"$out$(%s)\"\n", snippet)
	}
	b.WriteString("\necho \"$out\"\n")
	return b.String()
}

// RenderSlot executes the snippet of a single slot against the sample stdin
// payload and returns its rendered text. Empty slots render as "".
func RenderSlot(s slot.Slot) string {
	if s.IsEmpty() {
		return ""
	}
	script := "#!/bin/bash\ninput=$(cat)\n" + s.Block.Styles[s.StyleIdx].Snippet
	cmd := exec.Command("bash", "-c", script)
	cmd.Stdin = strings.NewReader(sampleInput())
	out, err := cmd.Output()
	if err != nil {
		return "(err)"
	}
	return string(out)
}

// Preview executes the generated script against a sample stdin payload and
// returns the resulting line (or an error message suitable for display).
func Preview(slots slot.List) string {
	if !hasFilled(slots) {
		return ""
	}
	cmd := exec.Command("bash", "-c", Generate(slots))
	cmd.Stdin = strings.NewReader(sampleInput())
	var out, errBuf bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &errBuf
	if err := cmd.Run(); err != nil {
		return fmt.Sprintf("(preview error: %s)", strings.TrimSpace(errBuf.String()))
	}
	return strings.TrimRight(out.String(), "\n")
}

func hasFilled(slots slot.List) bool {
	for _, s := range slots {
		if !s.IsEmpty() {
			return true
		}
	}
	return false
}

func sampleInput() string {
	return `{"model":{"display_name":"Opus 4.7"},"workspace":{"current_dir":"` + sampleCwd() + `"}}`
}

func sampleCwd() string {
	if cwd, err := os.Getwd(); err == nil {
		return cwd
	}
	return "/tmp"
}

// ScriptPath returns the absolute path where the generated script is stored.
func ScriptPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "claustomize", "statusline.sh"), nil
}

// SettingsPath returns the path to Claude Code's user settings.json.
func SettingsPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".claude", "settings.json"), nil
}

// Install writes the generated script to disk and updates settings.json to
// reference it. Existing settings.json fields are preserved.
func Install(slots slot.List) error {
	scriptPath, err := ScriptPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(scriptPath), 0o755); err != nil {
		return fmt.Errorf("create script dir: %w", err)
	}
	if err := os.WriteFile(scriptPath, []byte(Generate(slots)), 0o755); err != nil {
		return fmt.Errorf("write script: %w", err)
	}

	settingsPath, err := SettingsPath()
	if err != nil {
		return err
	}
	if err := updateSettings(settingsPath, scriptPath); err != nil {
		return fmt.Errorf("update settings: %w", err)
	}
	return nil
}

func updateSettings(settingsPath, scriptPath string) error {
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return err
	}

	settings := map[string]any{}
	if data, err := os.ReadFile(settingsPath); err == nil && len(data) > 0 {
		if err := json.Unmarshal(data, &settings); err != nil {
			return fmt.Errorf("parse existing settings: %w", err)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}

	settings["statusLine"] = map[string]any{
		"type":    "command",
		"command": scriptPath,
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(settingsPath, append(out, '\n'), 0o644)
}
